more hacks

diff --git a/.github/workflows/macos-build.yaml b/.github/workflows/macos-build.yaml
--- a/.github/workflows/macos-build.yaml
+++ b/.github/workflows/macos-build.yaml
@@ -39,29 +39,34 @@ jobs:
           ## brew install pkg-config glib gettext
 
           # Homebrew has no formula for gimp, but has "casks"
-          # We need the development files for gimp-3.0 to build against, a special cask.
-          # See https://formulae.brew.sh/cask/gimp@dev
-          brew install --cask gimp@dev
+          # We need the library gimp-3.0 to build resynthesizer against.
+          # See https://formulae.brew.sh/cask/gimp
+          # We don't want the gimp@dev cask which is the latest unreleased version of GIMP.
+          brew install --cask gimp
 
           python -m pip install --upgrade pip
           python -m pip install meson ninja
 
-      #- name: Prepare pkg-config for Homebrew dependencies
-      #  run: |
-      #    # Ensure Homebrew-provided .pc files are visible to pkg-config.
-      #    echo "PKG_CONFIG_PATH=$(brew --prefix)/lib/pkgconfig:$(brew --prefix)/share/pkgconfig:$(brew --prefix gimp)/lib/pkgconfig:${PKG_CONFIG_PATH}" >> "$GITHUB_ENV"
+      - name: Prepare pkg-config for Homebrew dependencies
+        run: |
+          # Ensure Homebrew-provided .pc files are visible to pkg-config.
 
-      #- name: Validate gimp-3.0 pkg-config module
-      #  env:
-      #    PKG_CONFIG_PATH: ${{ env.PKG_CONFIG_PATH }}
-      #  run: |
-      #    if ! pkg-config --exists gimp-3.0; then
-      #      echo "Expected pkg-config module 'gimp-3.0' was not found."
-      #      echo "Current PKG_CONFIG_PATH: $PKG_CONFIG_PATH"
-      #      echo "Available gimp-related .pc files under Homebrew:"
-      #      find "$(brew --prefix)" -path '*/pkgconfig/*.pc' -name '*gimp*.pc' -print | sort || true
-      #      exit 1
-      #    fi
+          # Homebrew installs the libraries to the application bundle
+          ls -al /Applications/GIMP.app/Contents/Resources/lib
+
+          echo "PKG_CONFIG_PATH=$(brew --prefix)/lib/pkgconfig:$(brew --prefix)/share/pkgconfig:$(brew --prefix gimp)/lib/pkgconfig:${PKG_CONFIG_PATH}" >> "$GITHUB_ENV"
+
+      - name: Validate gimp-3.0 pkg-config module
+        env:
+          PKG_CONFIG_PATH: ${{ env.PKG_CONFIG_PATH }}
+        run: |
+          if ! pkg-config --exists gimp-3.0; then
+            echo "Expected pkg-config module 'gimp-3.0' was not found."
+            echo "Current PKG_CONFIG_PATH: $PKG_CONFIG_PATH"
+            echo "Available gimp-related .pc files under Homebrew:"
+            find "$(brew --prefix)" -path '*/pkgconfig/*.pc' -name '*gimp*.pc' -print | sort || true
+            exit 1
+          fi
 
       - name: Show tool versions
         env:
